// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0kY02I9NHEUWnQuLq7P3BzgG4lfklc-M',
    appId: '1:109488680522:web:695f81e4ba3bfb9fd800b3',
    messagingSenderId: '109488680522',
    projectId: 'ros2flutter',
    authDomain: 'ros2flutter.firebaseapp.com',
    databaseURL: 'https://ros2flutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ros2flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1TesLXX6oK_Kxq7EHF48rb9Y_YZ5dp-Y',
    appId: '1:109488680522:android:dc4f8895420b4bbdd800b3',
    messagingSenderId: '109488680522',
    projectId: 'ros2flutter',
    databaseURL: 'https://ros2flutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ros2flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpx7ZdrHmU-XwYtuR150J20eFcG8nXp5I',
    appId: '1:109488680522:ios:9c51b425b9ef5c2cd800b3',
    messagingSenderId: '109488680522',
    projectId: 'ros2flutter',
    databaseURL: 'https://ros2flutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ros2flutter.appspot.com',
    iosClientId: '109488680522-uemaj6mqr8j0u55ip2u4cd9ubkqhgo1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.ros2Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpx7ZdrHmU-XwYtuR150J20eFcG8nXp5I',
    appId: '1:109488680522:ios:9c51b425b9ef5c2cd800b3',
    messagingSenderId: '109488680522',
    projectId: 'ros2flutter',
    databaseURL: 'https://ros2flutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ros2flutter.appspot.com',
    iosClientId: '109488680522-uemaj6mqr8j0u55ip2u4cd9ubkqhgo1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.ros2Flutter',
  );
}
